function [fitresult, gof] = gaussFit(plot_xaxis, fit_cut)
%CREATEFIT(PLOT_XAXIS,FIT_CUT)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : plot_xaxis
%      Y Output: fit_cut
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 11-Apr-2021 17:41:50


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( plot_xaxis, fit_cut );

% Set up fittype and options.
ft = fittype( 'gauss1' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Algorithm = 'Trust-Region';
opts.Display = 'Off';
opts.Lower = [-Inf -Inf 0];
opts.Normalize = 'on';
opts.StartPoint = [31.9549788141404 6.36889550116903e-12 0.260793401452446];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
toplot = false;
if(toplot)
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'fit_cut vs. plot_xaxis', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'plot_xaxis', 'Interpreter', 'none' );
ylabel( 'fit_cut', 'Interpreter', 'none' );
grid on
end


